Web dev
flatly-pw/backend pull request #28
Opened 2024-02-03 17:42 UTC by zniwiarzxxx

2024-02-03 18:13 UTC, zniwiarzxxx commented on src/main/java/pw/react/backend/models/domain/Flat.kt
> +    val thumbnailUrl: String?,
ups to nie

2024-02-03 22:42 UTC, Szymon022 commented on src/main/java/pw/react/backend/controller/FlatController.kt
> +        var flatOwner = flatOwnerRepository.findByEmail(email)?.toDomain()
Lepiej to przeniesc do serwisu skoro juz go masz

2024-02-03 22:42 UTC, Szymon022 commented on src/main/java/pw/react/backend/exceptions/FlatValidationException.java
> +public class FlatValidationException extends RuntimeException {
Czemu java? :p

2024-02-03 22:42 UTC, Szymon022 commented on src/main/java/pw/react/backend/models/domain/Address.kt
> +fun Address.toEntity() = AddressEntity(
Możesz też dodać AddressDto.toDomain() - może się przydać

2024-02-04 15:50 UTC, Szymon022 requested changes

2024-02-04 15:50 UTC, Szymon022 commented on src/main/java/pw/react/backend/controller/FlatController.kt
> +        val fileDownloadUri = ServletUriComponentsBuilder.fromCurrentContextPath()
`FlatImageService` ma w sobie metodę to generowania urla obrazka - trzeba to tylko tu wywołać.

2024-02-04 15:50 UTC, Szymon022 commented on src/main/java/pw/react/backend/services/FlatImageService.kt
> +            val newFlatImage = FlatImage("-1", fileName, imagetype, imagefile.bytes )
Zamiast id przekaż nulla - wtedy jpa generuje sobie id

2024-02-04 15:52 UTC, zniwiarzxxx commented on src/main/java/pw/react/backend/exceptions/FlatValidationException.java
> +public class FlatValidationException extends RuntimeException {
bo skopiowane lol

2024-02-04 19:53 UTC, Szymon022 approved these changes

2024-02-04 19:54 UTC, merged